[package]
name = "my_project"
version = "0.1.0"
authors = ["raihanrafif200095@gmail.com"]
edition = "2018"

[dependencies]
# Add your dependencies here, for example:
# serde = "1.0"
rayon-core = "1.11"
